### ISSUE TITLE
BUG: "No Compatible Sources Found"

### ISSUE THREAD

**Issue by stormr2010** [Twoure/lmwt-kiss.bundle#3]
Hi Twoure

After the selection menu into the video sources. The channel does not list the videos sources as it would normally based off the list of sources from the Unsupported Services bundle. Instead it displays 
"No Compatible Sources Found"

Steps I have checked:

 1) I have checked the main primewire.ag website through a browser and it seems to be working based off the sources available.
2) Updated Plex server to see if there were any differences. Result: None
3) Rolled back a version  of Plex server that has previously worked with this channel. Result: Still not working

Hoping for your guidance and support.

Thanks

StormR2010

**Comment by scott20j** [comment]
I also have encountered this problem. Following advice from this link I changed goto.php in the init.py to gohere.php https://forums.plex.tv/discussion/265246/primewire-channels

I did not change anything in the Servicelist.pinfo like suggested but after a restart it works again.

**Comment by stormr2010** [comment]
Thanks Scott. I have followed the instructions and it's back up and running. Hoping Twoure updates the source so theses changes are reflected in the channel.

**Comment by aantiix** [comment]
Just to clarify, this isn't an issue isolated to Primewire. I get the same message using the UnsupportedService bundle with FMovies channel as well, which also started at the same time.

**Comment by Twoure** [comment]
Fixed in https://github.com/Twoure/lmwt-kiss.bundle/commit/6bfbfce3638e3b97c76f393d16051dc4e7ed28eb.
