### ISSUE TITLE
current version is not working . using Version 1.7.5.4035 plex server . 

### ISSUE THREAD

**Issue by codcheeks** [Twoure/lmwt-kiss.bundle#5]
thanks for all the hard work, just that current version is not working on plex server Version 1.7.5.4035, keeps coming up channel not responding. looking forward to your fix. thanks again for all the work.

**Comment by scott20j** [comment]
I am on that version of plex and my channel is working. Have you updated
the service bundle via the uss channel? Could be your services are out of
date for the channel.

**Comment by scott20j** [comment]
You might also check that your channel is up to date

**Comment by Twoure** [comment]
@codcheeks PMS v1.7.5 doesn't handle channel transcoding properly for some Linux distributions.  Refer to [Comment_1487419](https://forums.plex.tv/discussion/comment/1487419/#Comment_1487419) for more info.

**Comment by codcheeks** [comment]
thanks all is well again
